[project]
name = "AndroHiker"
version = "0.1.0"
description = "Useful tools and scripts for hacking Android phones"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "androguard>=4.1.3",
]
